version: '3.6'

services:
  web:
    image: "node:carbon"
    user: "node"
    depends_on:
      - db
    working_dir: /home/node/app
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    command: "yarn start"
  watch:
    image: "node:carbon"
    user: "node"
    depends_on:
      - web
    working_dir: /home/node/app
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    links: 
      - "web:proxy"
    command: "yarn watch"